### ISSUE TITLE
ValueError: images do not match

### ISSUE THREAD

**Issue by EON-II** [Jon-Becker/nft-generator-py#16]
Generating 11 unique NFTs...
Traceback (most recent call last):
  File "index.py", line 110, in <module>
    generate_unique_images(11, {
  File "index.py", line 83, in generate_unique_images
    main_composite = Image.alpha_composite(layers[0], layers[1])
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2882, in alpha_composite
    return im1._new(core.alpha_composite(im1.im, im2.im))
ValueError: images do not match

continuously having this issue even though i checked and all files/directories match. 
[index.txt](https://github.com/Jon-Becker/nft-generator-py/files/7766623/index.txt)

**Comment by Jon-Becker** [comment]
The image layers must be the exact same size. IE: 1000x1000.
