### ISSUE TITLE
Errno2: No such file or directory for Metadata

### ISSUE THREAD

**Issue by CptJackieSparrow** [Jon-Becker/nft-generator-py#24]
Traceback (most recent call last):
  File "/nft-generator-py-main/index.py", line 225, in <module>
    "description": "Space Cowboys NFT Collection"
  File "/nft-generator-py-main/index.py", line 57, in generate_unique_images
    with open('./metadata/all-objects.json', 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: './metadata/all-objects.json'

**Comment by CptJackieSparrow** [comment]
Nvm, worked my way out.
I've just changed metadata folders absolute path.
