### ISSUE TITLE
Can't open JSON?

### ISSUE THREAD

**Issue by CptJackieSparrow** [Jon-Becker/nft-generator-py#50]
Traceback (most recent call last):
  File "PATH\nft-generator-py-main\generate.py", line 147, in <module>
    generate_unique_images(int(args.amount), loadJSON(args.config))
  File "PATH\nft-generator-py-main\lib\util\io.py", line 9, in loadJSON
    contents = json.loads("".join(pathFile.readlines()))
  File "C:\Users\PATH\miniconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\PATH\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\PATH\miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 38 column 3 (char 9226)

I'm having this error when i try to python generate.py --amount 222 --config config.json

**Comment by Jon-Becker** [comment]
Seems like you have an extra comma on line 36 😀

**Comment by CptJackieSparrow** [comment]
Damn, sorry to even bother you man.
Ty for the awesome ultra quick reply.

**Comment by CptJackieSparrow** [comment]
Hey man, i've did the incompatibilities as shown at top.
Do i have to manually enter each trait's compatibility? As in this list format, it doesn't exclude lists from list?

**Comment by Jon-Becker** [comment]
Correct, the value of an incompatibility cannot be a list as of this version. I can probably update it for you if you'd like

**Comment by CptJackieSparrow** [comment]
> Correct, the value of an incompatibility cannot be a list as of this version. I can probably update it for you if you'd like

Dude that’ll be terrific.
I’ve been manually making it for 3 days, but couldn’t even made it to half 😂

**Comment by CptJackieSparrow** [comment]
> Correct, the value of an incompatibility cannot be a list as of this version. I can probably update it for you if you'd like

Sorry to bother, though are you able to make the update Jon?

**Comment by Jon-Becker** [comment]
Hey! Will tackle this weekend. Sorry, been a bit busy!

**Comment by CptJackieSparrow** [comment]
You da best!
